language: python
jobs:
    include:
        - python: 2.6
          dist: trusty
        - python: 2.7
          dist: trusty
        - python: 3.3
          dist: trusty
        - python: 3.6
          dist: trusty
        - python: 3.9-dev
          dist: bionic
git:
    depth: 1
script:
    - python -c "import sqlmap; import sqlmapapi"
    - python sqlmap.py --smoke
    - python sqlmap.py --vuln
